<span class="main-page-modal-container">
    <div class="main-page-modal-wrapper">
        <img class="main-page-modal-image" src="https://wp4all.co.il/wp-content/uploads/2019/06/%D7%AA%D7%9E%D7%95%D7%A0%D7%94-%D7%A6%D7%95%D7%A8-%D7%A7%D7%A9%D7%A8.png" alt="Contact Us Image">
        <form class="main-page-modal-form">
            <div>
                Contact us
            </div>
            <input placeholder="Username">
            <input placeholder="Email">
            <textarea placeholder="Message..."></textarea>
            <button type="button" class="main-page-modal-form-button">
                Send message →
            </button>
            <div class="main-page-modal-form-button-container">
                <button id="button-cancel-modal-session">Cancel for this session</button>
                <button id="button-cancel-modal-fever">Cancel forever</button>
            </div>
        </form>
    </div>
    <div class="main-page-modal-backdrop"></div>
</span>
<script type="text/x-magento-init">
    {
        "*": {
            "alias": {}
        }
    }
</script>
